name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install --no-audit --no-fund --no-optional --loglevel=error
      - name: Eslint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Install libgtk2
        run: apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Test e2e
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: yarn serve
          wait-on: 'http://localhost:4173/'